config/routes.rb
Rails.application.routes.draw do
  get 'static/lookalikes_show'
  resources :look_a_likes
  resources :suburbs
  resources :events
  resources :events_look_a_likes
  resources :users
  resources :look_a_likes do
    resources :suburbs
  end

  resources :look_a_likes do
    resources :events
  end

  devise_for :users,  path: "", path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "pages#home", as: :root


  get "/profile", to: "users#user_profile", as: "user_profile"
  post "/profile/info", to: "users#update"
  patch "/profile/info", to: "users#update"
  put  "/profile/info", to: "users#update"
  get "/profile/info/edit", to: "users#edit_profile_info", as: "edit_profile_info"


  get "/profile/lookalike", to: "users#user_look_a_like", as: "user_look_a_like"
  get "/profie/loolalike/events", to: "users#user_look_a_like_events", as: "user_look_a_like_events"
  post "/profile/lookalike", to: "users#update"
  patch "/profile/lookalike", to: "users#update"
  put  "/profile/lookalike", to: "users#update"
  get "/profile/lookalike/edit", to: "users#look_a_like_form", as: "look_a_like_form"






  get "/lookalikes", to: "look_a_likes#index"

  get "/payments/success", to: "payments#success"

  get "/user_events", to: "events#user_events", as: "user_events"

  get "/submit_interest", to: "events#submit_interest", as: "submit_interest"

  get "/remove_suburb", to: "users#remove_suburb", as: "remove_suburb"

  get "/respond_interest", to: "events#respond_interest", as: "respond_interest"


  get "/suburbs/edit", to: "suburbs#edit", as: "edit_suburbs"

  get "/select_movie", to: "events#select_movie", as: "select_movie"

  get "/movies", to: "movies#index", as: "movies"

  get "/add_movie", to: "movies#add_movie", as: "add_movie"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




  belongs_to :address, optional: true
  belongs_to :look_a_like, optional: true
  belongs_to :image, optional: true

  has_many :events

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :look_a_like, update_only: true
  accepts_nested_attributes_for :image

  has_one_attached :image
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user
    before_action :set_events, only: [:user_profile_lookalike, :user_look_a_like, :user_look_a_like_events]
    before_action :set_look_a_like, only: [:user_look_a_like, :remove_suburb]
    before_action :set_look_a_like_images, only: [:user_look_a_like, :look_a_like_form, :remove_suburb]
    before_action :authenticate_user!

    def user_profile
    end




    def user_look_a_like
    end

    def user_look_a_like_events
    end

    def edit_profile_info
        render "info_form"
    end




    def user_profile_lookalike

    end



    def edit_profile_lookalike
    end

    def look_a_like_form
    end



    
    def update
        

        if @user.update(user_params)
            redirect_to "/profile"
        else
         render "/edit_profile_info", error: "Please try again"
        end
    end


    def remove_suburb

        current_user.look_a_like.suburbs.delete(Suburb.find(params[:format]))

        render "user_look_a_like"
        


    end



    

    private

    def set_user
        @user = current_user
    end


    def set_events
        @events = Event.all
    end


    def set_look_a_like
        @look_a_like = @user.look_a_like
    end


    def set_look_a_like_images
        if @user.look_a_like != nil
        if @user.look_a_like.images != nil
            @images = @user.look_a_like.images
        end
        end
    end


    def user_params
        params.require(:user).permit(:first_name, :last_name, :image, address_attributes: [:street_number, :street_name, suburb_attributes: [:name, :postcode]], look_a_like_attributes: [:bio, :id, images: []])
    end

end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |user_form| %>

  
    <div class="field">
        <%= user_form.label :first_name %>
        <%= user_form.text_field :first_name %>
    </div>
  
    <div class="field">
        <%= user_form.label :last_name %>
        <%= user_form.text_field :last_name %>
    </div>
  
    <%= user_form.fields_for :address, Address.new do |address_form| %>
    <div class="field">
      <%= address_form.label :street_number %>
      <%= address_form.text_field :street_number %>
      <%= address_form.label :street_name %>
      <%= address_form.text_field :street_name %>
  
      <%= address_form.fields_for :suburb, Suburb.new do |suburb_form| %>
        <%= suburb_form.label :name %>
        <%= suburb_form.text_field :name %>
        <%= suburb_form.label :postcode %>
        <%= suburb_form.text_field :postcode %>
      <% end %>
    </div>
    <% end %>
  
  </div>
  
    <div class="actions">
      <%= user_form.submit %>
    </div>
  <% end %>

app/views/users/_info_form.html.erb
<%= form_with(model: @user, local: true) do |user_form| %>
  <div class="flex px-10 pt-44 items-center font-sans overflow-hidden flex-col">

    <% if current_user.image.attached? %>
   

        <div class="round overflow-hidden rounded-lg shadow-lg flex justify-center">
        <%= image_tag(@user.image, :class => "picture flex flex-wrap") %>
        </div>

    <% end %>


    <label class="rounded-full py-3 px-6 bg-yellow-200 hover:bg-red-300">
      Add image
      <span style="display:none;">
        <%= user_form.file_field :image %>
      </span>
    </label>

  
    <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col">
        <%= user_form.label :first_name %>
        <%= user_form.text_field :first_name %>
    </div>
  
    <div class="field p-10 flex items-left font-sans overflow-hidden flex-col">
        <%= user_form.label :last_name %>
        <%= user_form.text_field :last_name %>
    </div>
  
    
    <%= user_form.fields_for :address, Address.new do |address_form| %>
      <div class="field p-10 flex items-left font-sans overflow-hidden flex-col">
        <%= address_form.label :street_number %>
        <%= address_form.text_field :street_number %>
      </div>
      <div class="field p-10 flex items-left font-sans overflow-hidden flex-col">
        <%= address_form.label :street_name %>
        <%= address_form.text_field :street_name %>
      </div>
    
        <%= address_form.fields_for :suburb, Suburb.new do |suburb_form| %>
          <div class="field p-10 flex items-left font-sans overflow-hidden flex-col">
          <%= suburb_form.label "suburb" %>
          <%= suburb_form.text_field :name %>
          </div>
          <div class="field p-10 flex items-left font-sans overflow-hidden flex-col">
          <%= suburb_form.label :postcode %>
          <%= suburb_form.text_field :postcode %>
          </div>
        <% end %>
      </div>
    <% end %>
 
  
    <div class="actions flex justify-center pb-40 pt-20">
      <%= user_form.submit "Update" %>
    </div>

  </div>
<% end %>

<%= image_tag "gb2.jpg" %>

app/views/users/_look_a_like_form.html.erb
<% if @user.look_a_like != nil %>



    <div class="m-20 p-10">
    <% (0...@images.count).each do |img| %>
        <div class="square overflow-hidden rounded-lg shadow-lg flex justify-center">
            <%= image_tag(@images[img], :class => "") %>
        </div>

    <% end %>
    </div>


    <%= form_with(model: @user, local: true) do |user_form| %>

        <div class="actions flex flex-col justify-center pb-40 pt-20">

            <%= user_form.fields_for :look_a_like do |lookalike_form| %>

                <div class="flex items-center font-sans overflow-hidden flex-col">

                
                    <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col justify-center ">
                        <label class="rounded-full py-3 px-6 bg-yellow-200 hover:bg-red-300">
                            Select images
                            <span style="display:none;">
                                <%= lookalike_form.file_field :images, multiple: true %>
                            </span>
                        </label>
                    </div>




                    <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col justify-center ">
                        <%= lookalike_form.text_field :bio %> 
                    </div>

                </div>

            <% end %>

            <div class= "flex justify-center">
                <%= user_form.submit "Update" %>
            </div>

        </div>

    <% end %>












    <div class="m-12">
        <h2 class="flex justifyer-cent">Suburbs</h2>

        <div class="overflow-x-auto">
            
            <div class="min-w-screen bg-gray-100 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">
                        <th class="py-2 px-4 text-left">name</th>
                        <th class="py-2 px-4 text-left">postcode</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>

                        <% if @user.look_a_like.suburbs != nil %>

                            <% @user.look_a_like.suburbs.each do |suburb| %>

                                <tr>
                                    <td class="m-12"><%= suburb.name %></td>
                                    <td class="m-9"><%= suburb.postcode %></td>
                                    <td class="m-9"><%= link_to 'Remove Suburb', remove_suburb_path(suburb) %></td>
                                </tr>




                            <% end %>

                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>





<div class="p-32">
    <%= link_to 'Suburb', new_suburb_path %>
</div>







<% end %>

app/views/users/_user_profile_lookalike.html.erb
<h1 class="flex justify-center m-10 text-5xl">My LookALike Details</h1>

<% if @user.look_a_like != nil %>



    <p class="flex justify-center">You are an active look-a-like</p>


    <div class="m-12">
        <h2 class="flex justifyer-cent">Invitations</h2>

        <div class="overflow-x-auto">
            
            <div class="min-w-screen bg-gray-100 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">
                        <th class="py-2 px-4 text-left">DATE</th>
                        <th class="py-2 px-4 text-left">TIME</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>

                        <% if @events != nil %>

                            <% @events.each do |event| %>

                                <p> <% event.look_a_likes %> </p>

                                <% for item in event.events_look_a_likes %>
                                    <% if (item.invite == true) %>
                                        <tr>
                                        <td class="py-2 px-4 text-left"><%= event.date %></td>
                                        <td class="py-2 px-4 text-left"><%= event.time %></td>
                                        <td class="py-2 px-4"><%= link_to 'Show', event %></td>
                                        <td class="py-2 px-4"><%= link_to 'Edit', edit_event_path(event) %></td>
                                        <td class="py-2 px-4"><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                        </tr>
                                    <% end %>
                                <% end %>

                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
 
    </div>



    

    <div class="m-12">
        <h2 class="flex justifyer-cent">Requests</h2>

        <div class="overflow-x-auto">
            
            <div class="min-w-screen bg-gray-100 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">
                        <th class="py-2 px-4 text-left">DATE</th>
                        <th class="py-2 px-4 text-left">TIME</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>

                        <% if @events != nil %>

                            <% @events.each do |event| %>

                                <p> <% event.look_a_likes %> </p>

                                <% for item in event.events_look_a_likes %>
                                    <% if (item.host_accepted != true) && (item.look_a_like == current_user.look_a_like) %>
                                        <tr>
                                        <td class="py-2 px-4 text-left"><%= event.date %></td>
                                        <td class="py-2 px-4 text-left"><%= event.time %></td>
                                        <td class="py-2 px-4"><%= link_to 'Show', event %></td>
                                        <td class="py-2 px-4"><%= link_to 'Edit', edit_event_path(event) %></td>
                                        <td class="py-2 px-4"><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                        </tr>
                                    <% end %>
                                <% end %>

                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
 
    </div>








    <div class="m-12">
        <h2 class="flex justifyer-cent">Going</h2>

        <div class="overflow-x-auto">
            
            <div class="min-w-screen bg-gray-100 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">
                        <th class="py-2 px-4 text-left">DATE</th>
                        <th class="py-2 px-4 text-left">TIME</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>

                        <% if @events != nil %>

                            <% @events.each do |event| %>

                                <p> <% event.look_a_likes %> </p>

                                <% for item in event.events_look_a_likes %>
                                    <% if (item.look_a_like_accepted == true) && (item.look_a_like == current_user.look_a_like) %>
                                        <tr>
                                        <td class="m-12"><%= event.date %></td>
                                        <td class="m-9"><%= event.time %></td>
                                        <td class="m-9"><%= link_to 'Show', event %></td>
                                        <td class="m-9"><%= link_to 'Edit', edit_event_path(event) %></td>
                                        <td class="m-9"><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                        </tr>
                                    <% end %>  
                                <% end %> 

                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
 
    </div>









<% else %>
    <p>You are currently not an active look-a-like profile</p>

    <div class="flex px-10 pt-44 items-center font-sans overflow-hidden flex-col justify-center">
    <%= form_with(model: @user, local: true) do |user_form| %>

        <%= user_form.hidden_field :first_name, value: @user.first_name %>  


        <%= user_form.fields_for :look_a_like, LookALike.new do |lookalike_form| %> 
            <div class="field flex justify-center">
                <%= lookalike_form.label "bio" %> 
                <%= lookalike_form.text_field :bio %> 
            </div>
        <% end %>


        <div class="actions">
            <%= user_form.submit %>
        </div>

    <% end %>

    </div>
    
<% end %>

app/views/users/edit.html.erb
<%= render "info_form" %>

app/views/users/edit_look_a_like.html.erb
<% if @user.look_a_like != nil %>



    <div class="m-20 p-10">
    <% (0...@images.count).each do |img| %>
        <div class="square overflow-hidden rounded-lg shadow-lg flex justify-center">
            <%= image_tag(@images[img], :class => "") %>
        </div>

    <% end %>
    </div>


    <%= form_with(model: @user, local: true) do |user_form| %>

        <div class="actions flex flex-col justify-center pb-40 pt-20">

            <%= user_form.fields_for :look_a_like do |lookalike_form| %>

                <div class="flex items-center font-sans overflow-hidden flex-col">

                
                    <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col justify-center ">
                        <label class="">
                            Add image
                            <span style="display:none;">
                                <%= lookalike_form.file_field :images, multiple: true %>
                            </span>
                        </label>
                    </div>




                    <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col justify-center ">
                        <%= lookalike_form.text_field :bio %> 
                    </div>

                </div>

            <% end %>

            <div class= "flex justify-center">
                <%= user_form.submit "Update" %>
            </div>

        </div>

    <% end %>












    <div class="m-12">
        <h2 class="flex justifyer-cent">Suburbs</h2>

        <div class="overflow-x-auto">
            
            <div class="min-w-screen bg-gray-100 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">
                        <th class="py-2 px-4 text-left">name</th>
                        <th class="py-2 px-4 text-left">postcode</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>

                        <% if @user.look_a_like.suburbs != nil %>

                            <% @user.look_a_like.suburbs.each do |suburb| %>

                                <tr>
                                    <td class="m-12"><%= suburb.name %></td>
                                    <td class="m-9"><%= suburb.postcode %></td>
                                    <td class="m-9"><%= link_to 'Remove Suburb', remove_suburb_path(suburb) %></td>
                                </tr>




                            <% end %>

                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>






<%= link_to 'Suburb', new_suburb_path %>





<%= link_to 'Movies', movies_path %>





<% end %>

app/views/users/look_a_like_form.html.erb
<% if @user.look_a_like != nil %>


    <%= form_with(model: @user, local: true) do |user_form| %>

        <div class="actions flex flex-col justify-center pb-40 pt-20 font-mono mx-32">

            <%= user_form.fields_for :look_a_like do |lookalike_form| %>

                <div class="flex items-center font-sans overflow-hidden flex-col bg-gray-100">

                
                    <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col justify-center ">
                        <label class="rounded-full py-3 px-6 bg-yellow-200 hover:bg-red-300 font-mono">
                            Select images
                            <span style="display:none;">
                                <%= lookalike_form.file_field :images, multiple: true %>
                            </span>
                        </label>
                    </div>



                    <div class="justify-center flex flex-col bg-green-100 m-5">
                        <h2 class="justify-center flex font-mono">Write Bio</h2>
                        <div class="field m-3">
                            <%= lookalike_form.text_field :bio, class: "" %> 
                        </div>
                    </div>

                </div>

            <% end %>

            <div class= "flex justify-center">
                <%= user_form.submit "Update" %>
            </div>

        </div>

    <% end %>












    <div class="m-32 bg-gray-200">
        <h2 class="flex justify-center font-mono p-6 bg-yellow-200">Suburbs</h2>

        <div class="overflow-x-auto">
            
            <div class="bg-gray-100 py-4 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto mx-1">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">
                        <th class="py-2 px-4 text-left">name</th>
                        <th class="py-2 px-4 text-left">postcode</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>

                        <% if @user.look_a_like.suburbs != nil %>

                            <% @user.look_a_like.suburbs.each do |suburb| %>

                                <tr>
                                    <td class="m-12 px-4"><%= suburb.name %></td>
                                    <td class="m-9 px-4"><%= suburb.postcode %></td>
                                    <td class="px-4"><%= link_to 'Remove Suburb', remove_suburb_path(suburb) %></td>
                                </tr>




                            <% end %>

                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="py-1 justify-center font-mono">
            <%= link_to 'Add A Suburb', new_suburb_path, class: "flex justify-center bg-purple-300" %>
        </div>
    </div>





<div class="p-32 font-mono">
<%= link_to 'Movies', movies_path, class: "flex justify-center bg-purple-300" %>
</div>





<% end %>

app/views/users/user_information.html.erb
<h1>My Details</h1>

<h2>Last Name</h2>
<% if (current_user.first_name) != nil %>
    <p><%= current_user.first_name %></p>
<% else %>
    <p>You have not given a first name</p>
<% end %>

<h2>Last Name</h2>
<% if (current_user.last_name) != nil %>
    <p><%= current_user.last_name %></p>
<% else %>
    <p>You have not given a last name </p>
<% end %>

<h2>Address</h2>
<% if (current_user.address) != nil %>
    <p><%= current_user.address.street_number %></p>
    <p><%= current_user.address.street_name %></p>
    <p><%= current_user.address.suburb.name %></p>
    <p><%= current_user.address.suburb.postcode %></p>


<% else %>
    <p>You have not given an address</p>
<% end %>

<%= link_to "edit profile", edit_profile_path(current_user) %>

app/views/users/user_look_a_like.html.erb
<div class="my_look_a_like flex flex-col justify-center font-mono">
        <% if @look_a_like != nil %>



                <div class="m-20 p-10">
                        <% (0...@images.count).each do |img| %>
                                <div class="square overflow-hidden rounded-lg shadow-lg flex justify-center">
                                        <%= image_tag(@images[img], :class => "") %>
                                </div>

                        <% end %>
                </div>


                <div class="mx-32 my-20 ">
                        <strong>Bio</strong>
                        <p class="break-all"><%= @look_a_like.bio %></p>
                </div>





                <div class="mx-32 my-20 ">
                        <strong>Available For The Following Locations</strong>
                        <div class="bg-purple-200 p-2">
                        <% @look_a_like.suburbs.each do |item| %>
                                <div class="bg-purple-100 m-1">
                                        <p class="my-4 break-all"><%= item.name + " " + item.postcode.to_s %></p>
                                </div>
                        <% end %>
                        </div>
                </div>
 



        <% else %>
                <p>You are currently not an active look-a-like profile</p>

                 <div class="flex px-10 pt-44 items-center font-sans overflow-hidden flex-col justify-center">
                <%= form_with(model: @user, local: true) do |user_form| %>

                        <%= user_form.hidden_field :first_name, value: @user.first_name %>  


                                <%= user_form.fields_for :look_a_like, LookALike.new do |lookalike_form| %> 
                                        <div class="field flex justify-center">
                                                <%= lookalike_form.label "bio" %> 
                                                <%= lookalike_form.text_field :bio %> 
                                        </div>
                                <% end %>


                                <div class="actions">
                                <%= user_form.submit %>
                                </div>

                        <% end %>

                </div>
    
        <% end %>



        
        <div class="flex justify-center my-14 py-3 px-5 mx-auto h-full text-center font-mono bg-purple-100">
                <%= link_to "Edit Look-a-Like Details", look_a_like_form_path(current_user) %>
        </div>


        <div class="flex justify-center my-14 py-3 px-5 mx-auto h-full text-center font-mono bg-purple-100">
                <%= link_to "Go To My Look-a-Like Events", user_look_a_like_events_path(current_user)  %>
        </div>
</div>

app/views/users/user_profile.html.erb
<div class="profile-container flex flex-col mx-20 my-52">



    <div class="flex px-16 pt-44 items-center font-sans overflow-hidden flex-col flex justify-center">
    <div class="flex bg-gray-50 bg-opacity-100 w-full mb-12 items-center font-sans overflow-hidden flex-col flex justify-center">


            <h1 class="font-bold text-2xl font-mono my-7">My Details</h1>




            <% if current_user.image.attached? %>

                <div class="round overflow-hidden rounded-lg shadow-lg flex justify-center">
                    <%= image_tag(@user.image, :class => "picture flex flex-wrap") %>
                </div>

            <% end %>




            <div class="field my-10 text-block flex items-left font-sans overflow-hidden flex-col">
                <h2 class="font-bold text-2xl font-mono" >First Name</h2>
                <% if (current_user.first_name) != nil %>
                    <p class="bg-gray-200 my-7 font-mono"><%= current_user.first_name %></p>
                <% else %>
                    <p class="bg-gray-200 my-7 font-mono">You have not given a first name</p>
                <% end %>
            </div>


            <div class="border-dotted w-3/4 border-t-2"></div>



            <div class="field text-block my-10 flex items-left font-sans overflow-hidden flex-col">
                <h2 class="font-bold text-2xl font-mono">Last Name</h2>
                <% if (current_user.last_name) != nil %>
                    <p class="bg-gray-200 my-7 font-mono"><%= current_user.last_name %></p>
                <% else %>
                    <p class="bg-gray-200 my-7 font-mono">You have not given a last name </p>
                <% end %>
            </div>


            <div class="border-dotted w-3/4 border-t-2"></div>


            <div class="field text-block my-10 flex items-left font-sans overflow-hidden flex-col">
                <h2 class="font-bold text-2xl font-mono ">Address</h2>
                <% if (current_user.address) != nil %>
                    <p class="bg-gray-200 mt-7 mb-2 font-mono"><%= current_user.address.street_number %></p>
                    <p class="bg-gray-200 my-2 font-mono"><%= current_user.address.street_name %></p>
                    <p class="bg-gray-200 my-2 font-mono"><%= current_user.address.suburb.name %></p>
                    <p class="bg-gray-200 my-2 font-mono"><%= current_user.address.suburb.postcode %></p>


                <% else %>
                    <p class="bg-gray-200 my-7 font-mono">You have not given an address</p>
                <% end %>
            </div>


            <div class="field text-block my-10 flex items-left font-sans overflow-hidden flex-col">
                <%= link_to "edit profile info", edit_profile_info_path(current_user) %>
            </div>



            <%= link_to "Go To My Look-a-Like Details", user_look_a_like_path(current_user) %>

    </div>
    </div>



</div>