config/routes.rb
Rails.application.routes.draw do
  get 'static/lookalikes_show'
  resources :look_a_likes
  resources :suburbs
  resources :events
  resources :events_look_a_likes
  resources :users
  resources :look_a_likes do
    resources :suburbs
  end

  resources :look_a_likes do
    resources :events
  end

  devise_for :users,  path: "", path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "pages#home", as: :root


  get "/profile", to: "users#user_profile", as: "user_profile"
  post "/profile/info", to: "users#update"
  patch "/profile/info", to: "users#update"
  put  "/profile/info", to: "users#update"
  get "/profile/info/edit", to: "users#edit_profile_info", as: "edit_profile_info"


  get "/profile/lookalike", to: "users#user_look_a_like", as: "user_look_a_like"
  get "/profie/loolalike/events", to: "users#user_look_a_like_events", as: "user_look_a_like_events"
  post "/profile/lookalike", to: "users#update"
  patch "/profile/lookalike", to: "users#update"
  put  "/profile/lookalike", to: "users#update"
  get "/profile/lookalike/edit", to: "users#look_a_like_form", as: "look_a_like_form"






  get "/lookalikes", to: "look_a_likes#index"

  get "/payments/success", to: "payments#success"

  get "/user_events", to: "events#user_events", as: "user_events"

  get "/submit_interest", to: "events#submit_interest", as: "submit_interest"

  get "/remove_suburb", to: "users#remove_suburb", as: "remove_suburb"

  get "/respond_interest", to: "events#respond_interest", as: "respond_interest"


  get "/suburbs/edit", to: "suburbs#edit", as: "edit_suburbs"

  get "/select_movie", to: "events#select_movie", as: "select_movie"

  get "/movies", to: "movies#index", as: "movies"

  get "/add_movie", to: "movies#add_movie", as: "add_movie"
end

app/models/event.rb
class Event < ApplicationRecord
    validates_presence_of :address

    belongs_to :address
    belongs_to :user

    has_many :events_look_a_likes, dependent: :destroy 
    has_many :look_a_likes, through: :events_look_a_likes

    has_many :movies_events, dependent: :destroy 
    has_many :movies, through: :movies_events

    accepts_nested_attributes_for :address
    accepts_nested_attributes_for :user
    accepts_nested_attributes_for :look_a_likes
    accepts_nested_attributes_for :movies
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :set_events
  before_action :set_events_look_a_like, only: [:show]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :show]

  before_action :set_movies, only: [:select_movie, :update, :new]

  require 'uri'
  require 'net/http'
  require 'openssl'
  require 'json'


  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.user_id = current_user.id
    @event.build_address
    @event.build_address.build_suburb

  end



  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    params[:movies].each do |item1|
      a = nil
      i = 0
      list = Movie.all
      while a == nil && i<(list).length-1
        if item1 == list[i].title
          a = list[i]
        end
        i = i + 1
      end

      if a == nil
        movie = Movie.create(title: item1)
      else
        movie = a
      end

      @event.movies.append(movie)
    end


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update

    respond_to do |format|
      if @event.update(event_params)

        format.html { redirect_to @event }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end


  
  def submit_interest
    @event = Event.find(params[:format])

    state = true
    @event.look_a_likes.each do |item|

      if item.user.id == current_user.id
        state = false

      end
    end

    if state == true
      @event.look_a_likes.append(current_user.look_a_like)
    end

  end




  def respond_interest
    @events_look_a_like = EventsLookALike.find(params[:format])


    if @events_look_a_like.host_accepted != true

      @events_look_a_like.host_accepted = true

      @events_look_a_like.save

    else

      @events_look_a_like.look_a_like_accepted = true
      @events_look_a_like.save

    end


    

  end

  
  def user_events

  end



  def select_movie

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_events
      @events = Event.all
    end

    def set_events_look_a_like

      @included = false
      @intersection = nil

      @event.events_look_a_likes.each do |item1|
        current_user.look_a_like.events_look_a_likes.each do |item2|
          if item1.id == item2.id
            @included = true
            @intersection = item1
          end
        end
      end

    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:date, :time, :price, :user_id, :listed, look_a_likes: [], movies: [], address_attributes: [:street_number, :street_name, suburb_attributes: [:name, :postcode]])
    end






    def set_movies
      url = URI("https://imdb8.p.rapidapi.com/actors/get-all-filmography?nconst=nm0000997")
  
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      request = Net::HTTP::Get.new(url)
      request["x-rapidapi-key"] = AUTH_DETAILS["IMDB_API_KEY"]
      request["x-rapidapi-host"] = AUTH_DETAILS["IMDB_API_HOST"]
      # request["x-rapidapi-key"] = IMDB_API_KEY
      # request["x-rapidapi-host"] = IMDB_API_HOST
  
      response = http.request(request)
      @movies = JSON.parse(response.read_body)["filmography"]
  
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="m-16 flex justify-center bg-gray-100">
  <%= form_with(model: @event, local: true) do |event_form| %>
    <div class="flex px-10 pt- pb-12 m-5 items-center font-sans overflow-hidden flex-col bg-gray-50">

      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="field sm:px-10 my-8 flex items-left font-sans overflow-hidden flex-col w-96">
        <%= event_form.label :date %>
        <div>
          <%= event_form.date_select :date %>
        </div>
      </div>

      <div class="field sm:px-10 my-8 flex items-left font-sans overflow-hidden flex-col w-96">
        <%= event_form.label :time %>
        <div>
          <%= event_form.time_select :time %>
        </div>
      </div>

      <%= event_form.fields_for :address do |address_form| %>
      <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col">
        <%= address_form.label :street_number %>
        <%= address_form.text_field :street_number %>
        <%= address_form.label :street_name %>
        <%= address_form.text_field :street_name %>

        <%= address_form.fields_for :suburb do |suburb_form| %>
          <%= suburb_form.label :name %>
          <%= suburb_form.text_field :name %>
          <%= suburb_form.label :postcode %>
          <%= suburb_form.text_field :postcode %>
        <% end %>
      </div>
      <% end %>

      
        <%= event_form.label :price %>
      <div class="field p-2 flex items-left font-sans overflow-hidden flex-col bg-purple-200">
        <%= event_form.number_field :price %>
      </div>

    </div>







    <div class="p-2 w-80 bg-purple-200 flex justify-center mx-44">
      <div class="bg-green-100 bg-opacity-80 h-48 overflow-hidden flex justify-center">
        <div class="overflow-auto flex flex-col w-full">
          <% for item in @movies %>
            <div class="flex flex-row items-center justify-between w-full">
              <p class="text-sm py-6"><%= item["title"] %></p>
   
              <input type="checkbox" name="movies[]" value="<%= item["title"] %>" />
            </div>
          <% end %>
        </div>
      </div>
    </div>



    <div class="field sm:p-10 flex items-left font-sans overflow-hidden flex-col">
      <%= event_form.label :listed %>
      <%= event_form.check_box :listed %>
    </div>


    <div class="actions">
      <%= event_form.submit %>
    </div>

  <% end %>

</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>


<div class="pt-20 mx-14">
<h1 class="bg-gray-100">Events</h1>

<div class="min-w-screen min-h-screen flex justify-center bg-purple-100 font-sans overflow-hidden">
  <table class="min-w-max w-full table-auto">
    <thead>
      <tr class="bg-purple-200 text-gray-600 uppercase text-sm leading-normal">
        <th>Date</th>
        <th>Time</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        
        <% if event.listed == true %>
          <tr class="border-b border-gray-200 hover:bg-gray-100">
            <td class="py-3 px-6 text-left whitespace-nowrap"><%= event.date %></td>
            <td class="py-3 px-6 text-left whitespace-nowrap"><%= event.time %></td>
            <td><%= link_to 'Show', event %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

</div>

app/views/events/new.html.erb
<h1 class="flex justify-center font-mono text-2xl p-5 m-5 bg-gray-200">New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/select_movie.html.erb
<%= form_with(model: @event, local: true) do |event_form| %>

   <div class="m-12">

        <div class="overflow-x-auto">
            
            <div class="min-w-screen bg-gray-100 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">

                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>



                            <% for item in @movies %>

                                <tr>
                                    <td class="m-9"><%= item["title"] %></td>
                                    <td class="m-9"><%= link_to 'Add movie', add_movie(item["title"]) %></td>
                                </tr>



                            <% end %>

                    </tbody>
                </table>
            </div>
        </div>
    </div>

<% end %>

app/views/events/show.html.erb
<div class="profile-container flex flex-col mx-24">
  <div class="flex px-16 pt-44 items-center font-sans overflow-hidden flex-col flex ">
    <div class="flex bg-gray-50 bg-opacity-100 w-full mb-12 p-5 font-sans overflow-hidden flex-col flex">


      <% if @event.user.first_name != nil && @event.user.first_name != nil %>
        <p class="my-4">
          <strong>Host Name:</strong>
          <%= @event.user.first_name + ' ' + @event.user.first_name%>
        </p>
      <% else %>
        <p class="my-4">
          <strong>User has not set name</strong>
        </p>
      <% end %>


      <div class="my-2 flex-col flex font-mono">
        <strong>Date:</strong>
        <%= @event.date %>
      </div>

      <p class="my-4">
        <strong>Time:</strong>
        <%= @event.time %>
      </p>

      <p class="my-4">
        <strong>Address:</strong>
        <%= @event.address.street_number + ' ' + @event.address.street_name + ' ' + @event.address.suburb.name + ' ' + @event.address.suburb.postcode.to_s %>
      </p>


      <p class="my-4">
        <strong>Payment:</strong>
        <% if @event.price != nil %>
          <%= @event.price.to_s + '.00 AUD' %>
        <% else %>
          <%= '.50 AUD' %>
        <% end %>
      </p>


      <p class="my-4">
        <strong>Gary Busey Movies:</strong>
        <ul>
          <% @event.movies.each do |movie| %>
            <li>
              <%= movie.title %>
            </li>
          <% end %>
        </ul>
      </p>


    </div>




      <% if @event.user != current_user %>


        <% if current_user.look_a_like != nil %>


          <% if @included %>

            <% userll = current_user.look_a_like.events_look_a_likes %>
            <% ans = userll[0] %>
            <% for item in userll %>
              <% if item.event == @event %>
                <% ans = item %>
              <% end %>
            <% end %>
            
            <% if ans.host_accepted == true%>
              <% if ans.host_accepted == true%>

                <p class="my-4">You will receive payment soon!<p>

              <% else %>

                <p class="my-4"> The host has accepted your expression of interest <p>

                <p class="my-4">Would you like to confirm your interest?<p>

                <%= link_to 'Confirm Expression of Interest', respond_interest_path(@intersection) %>

              <% end %>

            <% else %>

              <p class="my-4"> You have sent expression of interest </p>


          

              link_to 'Select a movie', select_movie_path()



            <% end %>

          <% else %>



            <p class="my-4">You can send an expression of interest<p>



            <%= link_to 'Send Expression of Interest', submit_interest_path(@event) %>


      



          <% end %>

        <% else %>
        <% end %>

      <% else %>

        <p class="my-4">This is one of your events </p>



        <div class="border-dotted border-2 w-full">
          <table class="min-w-max w-full table-auto font-mono">
          <p>LookALikes</p>
          <% @event.events_look_a_likes.each do |events_look_a_like| %> 

              <tr class="flex flex-col bg-gray-100 p-2">

                <td class="flex flex-row justify-between my-2 bg-gray-200">
                  <div class="flex flex-row justify-between w-full">
                    <div class="w-full flex justify-between bg-green-200 items-center m-2">
                      <%= events_look_a_like.look_a_like.user.first_name%>
                    </div>

                    <div class="w-full flex justify-between bg-green-200 items-center m-2">
                      <%=events_look_a_like.look_a_like.user.last_name%>
                    </div> 
                  </div>

                  <div class="">
                    <%= link_to 'Show Look-a-Like', events_look_a_like.look_a_like %>
                  </div> 
                </td>

                

                <td class="flex flex-row justify-between my-2">
                  <% if events_look_a_like.look_a_like_accepted != true %>
                    <p> LookALike Has Shown Interest</p>
                  <% else %>
                    <p> LookALike Confirmed Interest</p>
                  <% end %>

                  <div class=""><%= link_to 'Show', events_look_a_like %></div>
                </td>

              </tr>

          <% end %>

          </table>

        </div>



        <br>
        <br>
        <%= link_to 'Edit', edit_event_path(@event) %> 

      <% end %>

      <%= link_to 'Back', events_path %>






  </div>
</div>

app/views/events/user_events.html.erb
<div class="m-12 p-5 font-mono justify-center flex flex-col bg-gray-50 bg-opacity-60">

    <h1 class="justify-center flex m-4 text-4xl">My Events</h1>

    



    <div class="p-4 bg-purple-200 ">
        <h2 class="justify-center flex">Requests</h2>

        <div class="overflow-x-auto">
            
            <div class="min-w-screen bg-gray-100 flex items-center justify-center overscroll-auto font-sans overflow-hidden">
                

                <table class="min-w-max w-full table-auto font-mono">

                    <thead>
                        <tr class="bg-green-200 text-green-600 text-sm">
                        <th class="py-2 px-4 text-left">DATE</th>
                        <th class="py-2 px-4 text-left">TIME</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>

                        <% if @events != nil %>

                            <% @events.each do |event| %>
                            <% if user_signed_in? && event.user == (current_user) %>
                                <tr>
                                    <td><%= event.date %></td>
                                    <td><%= event.time.to_s(:time) %></td>
                                    <td><%= link_to 'Show', event %></td>
                                    <td><%= link_to 'Edit', edit_event_path(event) %></td>
                                    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                </tr>
                            <% end %>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>

    </div>




    <div class="bg-yellow-200 w-20">
        <%= link_to 'New Event', new_event_path %>
    </div>

</div>